### ISSUE TITLE
Bufferin node only seems to make StructuredBuffer<Float> 

### ISSUE THREAD

**Issue by everyoneishappy** [TheFuseLab/Fuse#12]
see StructuredBuffer input patch

**Comment by texone** [comment]
should be fixed

**Comment by everyoneishappy** [comment]
Seems to load the other type now, however only makes a buffer with the first value as far as I can tell.  Updated StructuredBufferInputParameter.vl to show this

**Comment by texone** [comment]
Was a bug in the sbloadprocessnode index input was set up as pingroup
